// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignments.sql

package dbgen

import (
	"context"
)

const acquireWriteLock = `-- name: AcquireWriteLock :exec
UPDATE sgsp_group_assignments SET closed=closed WHERE app_id=?1 AND group_key=?2
`

type AcquireWriteLockParams struct {
	AppID    string
	GroupKey string
}

func (q *Queries) AcquireWriteLock(ctx context.Context, arg AcquireWriteLockParams) error {
	_, err := q.db.ExecContext(ctx, acquireWriteLock, arg.AppID, arg.GroupKey)
	return err
}

const closeAssignment = `-- name: CloseAssignment :exec
UPDATE sgsp_group_assignments SET closed=true, closed_at=CURRENT_TIMESTAMP WHERE app_id=?1 AND group_key=?2
`

type CloseAssignmentParams struct {
	AppID    string
	GroupKey string
}

func (q *Queries) CloseAssignment(ctx context.Context, arg CloseAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, closeAssignment, arg.AppID, arg.GroupKey)
	return err
}

const getAssignment = `-- name: GetAssignment :one
SELECT app_version, owner_id, incarnation, endpoint_address, endpoint_server_name, closed FROM sgsp_group_assignments WHERE app_id=?1 AND group_key=?2
`

type GetAssignmentParams struct {
	AppID    string
	GroupKey string
}

type GetAssignmentRow struct {
	AppVersion         string
	OwnerID            string
	Incarnation        []byte
	EndpointAddress    string
	EndpointServerName string
	Closed             bool
}

func (q *Queries) GetAssignment(ctx context.Context, arg GetAssignmentParams) (GetAssignmentRow, error) {
	row := q.db.QueryRowContext(ctx, getAssignment, arg.AppID, arg.GroupKey)
	var i GetAssignmentRow
	err := row.Scan(
		&i.AppVersion,
		&i.OwnerID,
		&i.Incarnation,
		&i.EndpointAddress,
		&i.EndpointServerName,
		&i.Closed,
	)
	return i, err
}

const insertAssignment = `-- name: InsertAssignment :exec
INSERT INTO sgsp_group_assignments (app_id, group_key, app_version, owner_id, incarnation, endpoint_address, endpoint_server_name)
VALUES (?1,?2,?3,?4,?5,?6,?7) ON CONFLICT (app_id, group_key) DO NOTHING
`

type InsertAssignmentParams struct {
	AppID              string
	GroupKey           string
	AppVersion         string
	OwnerID            string
	Incarnation        []byte
	EndpointAddress    string
	EndpointServerName string
}

func (q *Queries) InsertAssignment(ctx context.Context, arg InsertAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, insertAssignment,
		arg.AppID,
		arg.GroupKey,
		arg.AppVersion,
		arg.OwnerID,
		arg.Incarnation,
		arg.EndpointAddress,
		arg.EndpointServerName,
	)
	return err
}

const lockAssignment = `-- name: LockAssignment :one
SELECT app_version, owner_id, incarnation, endpoint_address, endpoint_server_name, closed FROM sgsp_group_assignments WHERE app_id=?1 AND group_key=?2
`

type LockAssignmentParams struct {
	AppID    string
	GroupKey string
}

type LockAssignmentRow struct {
	AppVersion         string
	OwnerID            string
	Incarnation        []byte
	EndpointAddress    string
	EndpointServerName string
	Closed             bool
}

func (q *Queries) LockAssignment(ctx context.Context, arg LockAssignmentParams) (LockAssignmentRow, error) {
	row := q.db.QueryRowContext(ctx, lockAssignment, arg.AppID, arg.GroupKey)
	var i LockAssignmentRow
	err := row.Scan(
		&i.AppVersion,
		&i.OwnerID,
		&i.Incarnation,
		&i.EndpointAddress,
		&i.EndpointServerName,
		&i.Closed,
	)
	return i, err
}
