// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type SgspGroupAssignment struct {
	AppID              string
	GroupKey           string
	AppVersion         string
	OwnerID            string
	Incarnation        []byte
	EndpointAddress    string
	EndpointServerName string
	Closed             bool
	CreatedAt          string
	ClosedAt           sql.NullString
}
